### PR TITLE
Raymond development

### PR DESCRIPTION
**Pull request by Rhaypapenfuzz**
Create the about me servlet. Can be reached with http://localhost:8080/about?user=Ada@codeustudents.com

### CODE REVIEW

**Review by tsalako — CHANGES_REQUESTED** [review]
When done can you include a screenshot of the new page?

**Review by ChuyueSun — COMMENTED** [review]
I think everything looks good! Couldn't think of anything to change...

**Review by ChuyueSun — APPROVED** [review]

**Comment by Rhaypapenfuzz** [comment]
> When done can you include a screenshot of the new page?

**Review by tsalako — CHANGES_REQUESTED** [review]
Looks good. Can you include a screenshot of your new feature as well (styled text 2)?

**Comment by Rhaypapenfuzz** [comment]
This is how it looks like

**Review by tsalako — APPROVED** [review]
Looks great. Thanks man. Also great to meet you!

**Pull request merged**
