### PR TITLE
This will enable user to upload local images from their computer …

### PR DESCRIPTION
**Pull request by Rhaypapenfuzz**
…in addition to the uploading using the link of an image

### CODE REVIEW

**Comment by Rhaypapenfuzz** [comment]
Screenshot (14)
That's a screenshot with the upload button

**Comment by tsalako** [comment]
Does the upload button work? So if you uploaded an image (instead of putting a link to the image in the textbox) and hit submit does it appear on the page?

**Comment by Rhaypapenfuzz** [comment]
I am working on that feature right now. This is the initial pull request. I am making changes to messageServlet and Datastore to get that to work

**Review by tsalako — APPROVED** [review]
Feel free to merge

**Pull request merged**
