### PR TITLE
This html adds a draw chart function.

### PR DESCRIPTION
**Pull request by ChuyueSun**

### CODE REVIEW

**Review by tsalako — CHANGES_REQUESTED** [review]
Can you add a screenshot of the chart?

**Comment by ChuyueSun** [comment]
Screen Shot 2019-04-04 at 1 25 24 PM

**Comment by tsalako** [comment]
Ahh by screenshot I mean of the chart itself on localhost not the code.

**Comment by ChuyueSun** [comment]
Screen Shot 2019-04-04 at 1 34 26 PM

**Review by tsalako — APPROVED** [review]

**Pull request merged**
